name: Launching Noble World unit tests

on:
  push:
    branches:
      - "develop"

jobs:
  tests:
    name: Noble World Smart Contract Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js 20.18.0
        uses: actions/setup-node@v1
        with:
          node-version: 20.18.0

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: "node_modules"
          key: node_modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run Hardhat Unit Tests
        run: npx hardhat test
