name: Noble World Backend Tests

on:
  push:
    paths:
      - "backend/**"
    branches: ["develop"]
  pull_request:
    paths:
      - "backend/**"
    branches: ["develop"]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"
          cache-dependency-path: "./backend/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run Hardhat tests
        run: npx hardhat test
        env:
          PRIVATE_KEY_LOCALHOST_HARDHAT: ${{ secrets.PRIVATE_KEY_LOCALHOST_HARDHAT }}
          PRIVATE_KEY_BASE_SEPOLIA: ${{ secrets.PRIVATE_KEY_BASE_SEPOLIA }}
          PRIVATE_KEY_BASE_MAINNET: ${{ secrets.PRIVATE_KEY_BASE_MAINNET }}
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
          BASESCAN_API_KEY: ${{ secrets.INFURA_HOLESKY_RPC_URL }}
          PUBLIC_TEST_ADDRESS: ${{ secrets.PUBLIC_TEST_ADDRESS }}
